language: clojure

dist: trusty
sudo: false
jdk: oraclejdk10

deploy:
  api_key:
    secure: YRQz3OTuZ99a/ycPjbI/4x0RuLlhvLFHojsIZcmjyPPcNqhEQenmrzt9qbsaLi1HcVkkznJ6GbYR8D2BDiWNnVHocfvnB5bnO9IUca1IPHCQfW6xDQJnGpwioOqoeLPQz3UedVmf+FbNOeoJmCCcPsvNJhOwZKEtJiFtytf72jKqTri4BFmG1dHfRVx5BHSxIyALCzEphw2qXgHpxNT2YJ90kg8Kky7GWmVgKnlBIxUqyNG8DP7CqriIQxbSi5YeVRWj5txSOzfNZml/7YimGoKM7nEcVEcuOobz9p/5qPf+GG89zoAluK+R+TlHyjte7J4KIaJKUnu5XMJFijl5+JnK6CZaXIaOMxkqu7fpxosEzCn0MzpMk3FeP2VPx0frUotbzz24KV85qxTuy+ldDpKEfoK6dn6clYSm39yMvL88UZKbXl1CoUrQdZ4Uhhj1l2kXJO8MzyGDTlEPYF9M1OWMA7+KbcsJcky3o3/bnensDHYlu7vDr7O3z8dZ13opaA00+OvxlKzO/Xc55RdkRubhOG1Dc0sWgIO+o0UYbU7eNBM8oGpLA+yd8F8gwt9LXAgOjb4RfVw7+Hs/kw4mlZN0/XmfeS4hVOOzBOOOLyIxBJTb2vakGHcWBoW3x4zaHfKI2I1kFD05eELm591tMZSKwNWawzTrxyd2qwNvU8M=
